/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingFlowImport } from './routes/onboarding-flow'
import { Route as EditImport } from './routes/edit'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const OnboardingFlowRoute = OnboardingFlowImport.update({
  id: '/onboarding-flow',
  path: '/onboarding-flow',
  getParentRoute: () => rootRoute,
} as any)

const EditRoute = EditImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditImport
      parentRoute: typeof rootRoute
    }
    '/onboarding-flow': {
      id: '/onboarding-flow'
      path: '/onboarding-flow'
      fullPath: '/onboarding-flow'
      preLoaderRoute: typeof OnboardingFlowImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/onboarding-flow': typeof OnboardingFlowRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/onboarding-flow': typeof OnboardingFlowRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/onboarding-flow': typeof OnboardingFlowRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/edit' | '/onboarding-flow'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/edit' | '/onboarding-flow'
  id: '__root__' | '/' | '/edit' | '/onboarding-flow'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditRoute: typeof EditRoute
  OnboardingFlowRoute: typeof OnboardingFlowRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditRoute: EditRoute,
  OnboardingFlowRoute: OnboardingFlowRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/edit",
        "/onboarding-flow"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/edit": {
      "filePath": "edit.tsx"
    },
    "/onboarding-flow": {
      "filePath": "onboarding-flow.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
